project:
  type: website

website:
  title: Open EM Book
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Ultrasound Course"
        file: us-introduction.qmd

  sidebar:
    - title: "Ultrasound Course"
      style: "floating"
      background: dark
      contents:
        - section: "Introduction"
          contents:
            - us-introduction.qmd
            - us-prerequisites.qmd
            - us-content-and-objectives.qmd
            - us-meet-the-team.qmd
        - section: "Fundamentals of Ultrasound"
          contents:
            - us-fundamentals.qmd
            - us-ultrasound-101.qmd
            - us-padr.qmd
            - us-simplest.qmd
            - us-more-on-reflection.qmd
            - us-choose-of-probes.qmd
            - us-modes.qmd
            - us-artefacts.qmd
            - us-adverse-effects.qmd
            - us-fundamentals-thm.qmd
            - us-fundamentals-test.qmd

    - title: "How-To"
      contents:
        - howto.qmd
        # navigation items

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
