---
title: "Take Home Messages"
---

::: callout-tip
## Take Home Messages

-   Ultrasound are pressure waves propagating through tissues

-   Ultrasound probe is able to emit and receive ultrasounds

-   Ultrasounds are reflected by the tissues, when the incident ultrasound hits an interface (ie. a surface separating two media with different acoustic impedances)

-   Ultrasound devices are able to determine position of tissue structures by calculating their distance from the probe, based on the time between emission of ultrasound and reception of echo (time of transit)

-   Interface causing the most reflection is water-air, which reflect more than 99% of the incident ultrasound

-   The probes must been chosen depending on the area of exploration, the possible obstacles and the needed depth. Most available probes include:

    -   Linear high-frequency: for skin, superficial tissues, vessels, bones (sometimes pleura)

    -   Curvilinear low frequency: for abdomen (sometimes pleura)

    -   Sectorial (or phased array): for heart and brain (sometimes pleura)

-   B-mode is the most-used ultrasound mode (sometimes called 2D-mode). TM mode is mostly used to measure speeds and range of motion

-   Ultrasounds can generate artifacts, which must been taken into account for correct interpretation

-   Although no case of ultrasound imaging-induced injury has been reported, potential biological effects of ultrasound justify to reduce the exposition to risk of mechanical or thermal injuries by adequate tuning and, sometimes, reduction of time of exposure
:::
