---
title: "Modes"
---

The **modes** define how the ultrasound device will interpret the received reflected ultrasounds to produce an image. In this course, we will cover:

- A (amplitude) mode
- B (Brightness) mode
- TM (Time-Motion) mode

Doppler modes will not be covered.

## A-mode

The A mode was historically the first mode created. It is a one-dimension mode, as ultrasounds are emitted and received in only one direction.

How this mode works is very similar to what we covered on the previous chapter:
- the X-axis represents the time of transit, which corresponds to the distance between the probe and the target
- the Y-axis represents the amplitude of the reflected ultrasound

## B-mode

The B mode (for ***Brightness***, also called 2D mode) is the "classical" mode used for anatomical examination. The image represents a slice of the body section examined.

This mode is obtained by:

- emitting an ultrasound in a direction
- receiving the reflected ultrasounds and measuring their time of transit
- calculating the distance between the probe and the targets
- plotting the targets by a whit dot (the higher the amplitude, the brighter the dot)
- emitting a new ultrasound in another direction

## TM-mode

The TM mode (for Time-Motion) is also a one-directional mode, working similarly to the A-mode. However, in TM mode, the ultrasound measure one the axis is repeated over time, in order to identify motion.

In TM mode, the X axis is the time of acquisition, and the Y axis is the depth. This means that:
- a target at a fixed distance (eg. 5 cm) with no movement will be represented as a horizontal line at 5 cm of depth
- a target moving back and forth in the direction of the axis of ultrasound will be represented as a sinusoïd line
- a target moving back and forth perpendicularly to the axis of ultrasound will bass by the ultrasound beam, and after leave it, and so on back and forth. It will be represented as a dotted line.

TM is useful to measure movement distance or to compare distances (ex. diastolic and systolic ventricular diameter, inspiratory and expiratory diameters of the vena cava ...).
