---
title: "Prerequisites and certification"
---

## What should I know before enrolling?

This course is open to all healthcare workers, including physicians, nurses, midwives, paramedics, and allied health professionals. Whether you work in primary care, emergency medicine, obstetrics, or any other healthcare specialty, the skills you acquire in this course will help you include ultrasound imaging into everyday practice.

Therefore, no real prerequisite is necessary before enrolling. However, we do assume that students have a good general knowledge of emergency medicine. Furthermore, during the live lectures and workshops, the instructors consider the online content as already acquired by the students.

## Certification

We are committed to maintaining the highest standards of education and training, and as such, we place great emphasis on verifying that each student has acquired the necessary knowledge and skills before earning their certification. 

The certification is earned based on the results of both written and practical tests at the end of the course, along with commitment to the course along the training session.
