---
title: "Ultrasound 101"
---

## But, what is an ultrasound?

### Definition of ultrasounds

First thing first: what is *precisely* an ultrasound?

::: {.callout-note collapse="true"}
## What is an ultrasound?

An ultrasound is a **mechanical wave** (ie. cyclic variation of **air pressure** over **time** and **space**).
:::

### Amplitude, frequency, period

The ultrasounds are characterised by two values: **amplitude** and **frequency**:

-   the **amplitude** is the highest pressure obtained at the peak of the wave
-   the **frequency** is the number of entire cycles per time unit. Frequency is mostly measured in **Hertz (Hz)**, indicating the number of cycles per **second**.

The frequency is related to the **period** of the wave, which is the **duration** of a cycle. The frequency and period are related:

$$
Frequency = \frac{1}{Period}
$$

For example, a wave with a frequency of 2 Hz (meaning, two cycles per second) has a period of 0.5 seconds ($\frac{1}{2}$). A wave with a frequency of 40 Hz has a period of 0.025 seconds ($\frac{1}{40}$) or 25 milliseconds.

### Energy of the ultrasounds

The **energy** of an ultrasound depends on both the frequency and the amplitude:

-   the higher the frequency, the higher the energy
-   the higher the amplitude, the higher the energy

::: callout-tip
## Why it matters?

Choosing wisely the frequency and amplitude is essential to obtain the best image quality while limiting the potential adverse effects (see after).
:::
